### ISSUE TITLE
佬，下载完成后，docker有运行镜像，但是访问不了

### ISSUE THREAD

**Issue by 80576560** [honmashironeko/ARL-docker#1]
![image](https://github.com/honmashironeko/ARL-docker/assets/41313763/7df54a64-7957-4093-a73e-db2d2a8d4d8f)

**Comment by honmashironeko** [comment]
换成centos哦，ubuntu还没有适配

**Comment by 80576560** [comment]
docker运行，应该不挑主机环境吧

**Comment by honmashironeko** [comment]
会的，我实际测试，在ubuntu中遇到了DBus无法使用到问题，没看到什么解决方案，有可能是自带的docker存在问题，需要拉取其他库的第三方docker

**Comment by sh3d0ww01f** [comment]
ubuntu解决方法如下
 ```
apt install python
mv /bin/systemctl /bin/systemctl.bak
wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /bin/systemctl
sudo chmod a+x /bin/systemctl
```
参考文献如下:
`https://zhuanlan.zhihu.com/p/648578218`
``
