### ISSUE TITLE
docker  的linux登录密码是？

### ISSUE THREAD

**Issue by sumo166** [honmashironeko/ARL-docker#14]
![image](https://github.com/honmashironeko/ARL-docker/assets/47419184/102bb945-8873-4b64-814f-50775db87483)
老哥，给你收藏了，但是我设置了系统启动，自动进入docker的命令模式，linux的密码是多少啊

**Comment by honmashironeko** [comment]
没有密码吧

**Comment by sumo166** [comment]
> 没有密码吧

我设置了docker在系统启动时，自动启动docker，现在系统一打开就进入了，唉

**Comment by sumo166** [comment]
算了，我重新装系统了，下次要记得快照！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
