### ISSUE TITLE
进入docker容器执行sh出现安装失败！

### ISSUE THREAD

**Issue by sumo166** [honmashironeko/ARL-docker#16]
![image](https://github.com/honmashironeko/ARL-docker/assets/47419184/cd251cfb-bd4d-43ce-af29-08088960371b)

![image](https://github.com/honmashironeko/ARL-docker/assets/47419184/0691941e-9161-446b-996d-f8f9fa34f62a)

--> Processing Dependency: freetype >= 2.8-7 for package: fontconfig-2.13.0-4.3.el7.x86_64
Determining fastest mirrors
^C

**Comment by honmashironeko** [comment]
你输入了ctrl+c，把进程停了。。。重新运行
