### ISSUE TITLE
容器内set.sh运行缓慢

### ISSUE THREAD

**Issue by laaaaaaal** [honmashironeko/ARL-docker#18]
![屏幕截图 2024-07-17 101946](https://github.com/user-attachments/assets/48ba1ea8-345a-455c-b58f-7375fe47b329)
这个界面一直运行了3个小时这真的正常吗？

**Comment by honmashironeko** [comment]
这个当然不正常，根据截图，你当前在安装依赖，可能是网络在国内，目前已知大部分源被封禁，因此建议采用香港等网络环境安装，后续会尝试更新为本地安装。

**Comment by laaaaaaal** [comment]
挂了代理，快一点了
