### ISSUE TITLE
docker 安装完之后提示无效目标

### ISSUE THREAD

**Issue by Meo9y** [honmashironeko/ARL-docker#22]
<img width="1657" alt="image" src="https://github.com/user-attachments/assets/9a8b417b-2153-4cf5-9648-45f3803ea14b">
git clone https://github.com/honmashironeko/ARL-docker.git
安装之后 访问 web 建立任务就提示无效目标
<img width="924" alt="image" src="https://github.com/user-attachments/assets/8f5ee406-3781-4674-90da-f8e731c33f47">

**Comment by Meo9y** [comment]
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/f090d879-1c00-45c6-918a-bee0006cca87">

**Comment by Meo9y** [comment]
不支持带协议的目标

**Comment by honmashironeko** [comment]
ARL不支持带有https://前缀，删除即可
