### ISSUE TITLE
ERROR: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Mingjiexiaojiu** [honmashironeko/ARL-docker#25]
ERROR: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

这个怎么搞

**Comment by 2287635155** [comment]
没有科学上网

**Comment by honmashironeko** [comment]
换源，docker 又被禁了
