### ISSUE TITLE
安装成功，但是没有web站点，也没有镜像与容器

### ISSUE THREAD

**Issue by TajangSec** [honmashironeko/ARL-docker#27]
你好，我是Ubuntu 22.04，已经安装了docker，我属于境外网络。我正常执行脚本，一切正常运行，在最后出现这样的语句：

`HTTPSConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x71b391e44310>: Failed to establish a new connection: [Errno 111] Connection refused'))`
而且脚本后面显示的ARL_URL是个外网地址，这点不理解。
我看了镜像与容器，发现并没有ARL，这很奇怪

**Comment by honmashironeko** [comment]
这说明你docker没装上啊
