### ISSUE TITLE
卡在启动服务... 

### ISSUE THREAD

**Issue by hnximi** [honmashironeko/ARL-docker#5]
![image](https://github.com/honmashironeko/ARL-docker/assets/41935456/b0a2b45b-d2c6-4670-9362-565c892c2f6e)

**Comment by honmashironeko** [comment]
上面那个WARNING的是正常的哈，因为用的是root权限，都会提示的，他建议你用虚拟环境而已，不用管他

**Comment by honmashironeko** [comment]
如果长时间不动，可以手动运行一下命令，看看哪里报错

**Comment by hnximi** [comment]
![image](https://github.com/honmashironeko/ARL-docker/assets/41935456/61dda8d6-6b01-45e3-bad4-9a116bd60850)
权限问题吗，按照手动部署docker方式

**Comment by honmashironeko** [comment]
看报错应该是，用 sudo 试试

**Comment by honmashironeko** [comment]
目前 OK 了吗

**Comment by hnximi** [comment]
测试了两台vps都不行，一台腾讯云centos8的，一台阿里云ubuntu22，都会卡到启动服务这里，用的都是docker部署方式，但是本地使用centos7测试搭建成功

**Comment by honmashironeko** [comment]
那可能网络有问题，试试香港的机子

**Comment by hnximi** [comment]
用的一个国内的，一个新加坡的

**Comment by honmashironeko** [comment]
有空的话加我，我远程帮你看看吧

**Comment by huaxinhuaxin** [comment]
解决了么，我也是一样的问题

**Comment by newbeeboy1019** [comment]
![q](https://github.com/honmashironeko/ARL-docker/assets/130530339/8fdf7463-1a53-4ef2-a55b-d406504fbba0)
我是这样 访问不了

**Comment by newbeeboy1019** [comment]
![qq](https://github.com/honmashironeko/ARL-docker/assets/130530339/32aa7cfb-c056-4643-9c87-8a8507eb494f)
第一次报错是这样的 然后我又试了一次bash /root/arl/set.sh
就是上面那样的图片 访问不到

**Comment by laaaaaaal** [comment]
我在启动服务时发生这样的报错ERROR:systemctl:the ExecStartPre control process exited with error code
有大佬知道吗？

**Comment by laaaaaaal** [comment]
> 我在启动服务时发生这样的报错ERROR:systemctl:the ExecStartPre control process exited with error code 有大佬知道吗？

![屏幕截图 2024-07-17 220222](https://github.com/user-attachments/assets/782bb3d7-4f39-4a1f-bb1f-9e16a00f9cae)
我之前有这样的报错，我重新运行了set.sh貌似没问题了，但是卡在服务启动
