### ISSUE TITLE
重启后失效

### ISSUE THREAD

**Issue by helloworldbugs** [honmashironeko/ARL-docker#7]
docker版本的，重启之后，5003端口可以正常监听，但是访问不了，进docker重新执行`bash /root/arl/set.sh`报错如下
![image](https://github.com/honmashironeko/ARL-docker/assets/84578970/1068c2ba-5a83-43ab-8428-83445eb5a5e6)

**Comment by honmashironeko** [comment]
你是重启docker还是重启服务器，重启ARL是/opt/ARL/misc中有个m开头的文件
