### ISSUE TITLE
镜像重启失效

### ISSUE THREAD

**Issue by ll160803** [honmashironeko/ARL-docker#8]
在docker里面重启images，就失效了
<img width="847" alt="image" src="https://github.com/honmashironeko/ARL-docker/assets/88411423/6234f0d3-02ad-4a8e-a8da-04297ff192ed">
可以可以访问web，但是不能用，超时
<img width="1285" alt="image" src="https://github.com/honmashironeko/ARL-docker/assets/88411423/5f079a58-b60f-4718-bea7-ac08b09b8c70">
status
<img width="653" alt="image" src="https://github.com/honmashironeko/ARL-docker/assets/88411423/e3e27414-50c8-4d03-b52f-904cef16e0e7">
这个manager.sh 重启也报错：
ERROR:systemctl:the ExecStartPre control process exited with error code
docker安装如下：

**Comment by honmashironeko** [comment]
重启 docker 服务试试

**Comment by ll160803** [comment]
![image](https://github.com/honmashironeko/ARL-docker/assets/88411423/e302f67d-07b6-4e30-a6c7-6241924b8792)
b不知道为啥 还是不行

**Comment by honmashironeko** [comment]
说实话，我网上都查不到这个报错，我也没办法确认是什么问题了，建议源码安装使用看看吧

**Comment by ll160803** [comment]
好吧 我删了重装的images 先用着 不知道重启后报不报错 感谢大佬
