### ISSUE TITLE
在kali中重启失败

### ISSUE THREAD

**Issue by jjjxusbx** [honmashironeko/ARL-docker#9]
运行bash setup_docker.sh后输入SSH验证后出现下面问题
![屏幕截图 2024-06-08 131135](https://github.com/honmashironeko/ARL-docker/assets/146902099/2c42b151-0665-4fd2-b5db-b46c7b38388a)

**Comment by honmashironeko** [comment]
自行安装好docker、docker-compose之后用脚本部署
